### PR TITLE
atmos fixes to mining shuttle / reclaimer

### PR DESCRIPTION
**Pull request by ProphetCrow**
Description.

Adds tiny fans to airlock of reclaimer and a functional atmos system. 

:cl: Crow
- add: Added fun :D
- tweak: Tweaked fun
- fix: Fixed fun!
- remove: Removed fun :(

### CODE REVIEW

**Comment by redmushie** [comment]
image
The tile below the cursor has no grille or floor tile.

**Comment by redmushie** [comment]
Atmos looks good, tiny fans also.

**Review by redmushie — CHANGES_REQUESTED** [review]
Add a floor tile and grille over the passive vent pipe, then LGTM

**Comment by ProphetCrow** [comment]
> Add a floor tile and grille over the passive vent pipe, then LGTM

GTG

**Comment by redmushie** [comment]
I can't believe I only noticed this now, was this already the case? No grille here either (old pic)
image

**Pull request closed without merging**
